### ISSUE TITLE
How to set role for user?

### ISSUE THREAD

**Issue by xuxubla** [dektrium/yii2-rbac#106]
How to set role fo user? can see table auth_assignment, but I don't know hoy to fill it? Can this package do this? Or not?

**Comment by becology1100** [comment]
do you got any updates ??

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
