### ISSUE TITLE
ajax validation causing error "Headers already sent."

### ISSUE THREAD

**Issue by cornernote** [dektrium/yii2-rbac#133]
In `ItemControllerAbstract::performAjaxValidation()` it has this:

```
\Yii::$app->response->format = Response::FORMAT_JSON;
echo json_encode(ActiveForm::validate($model));
\Yii::$app->end();
```

It should become:

```
\Yii::$app->response->format = Response::FORMAT_JSON;
\Yii::$app->response->data = json_encode(ActiveForm::validate($model));
\Yii::$app->end();
```

More info here: https://github.com/yiisoft/yii2/issues/15782

**Comment by thiagotalma** [comment]
You can make a PR?

**Comment by cornernote** [comment]
seems someone beat me to it - https://github.com/dektrium/yii2-rbac/commit/748453654e69eedadb3aa87ba327f1c554061004#diff-e819dc2dea4990e56ef6cda913def831

**Comment by buttflattery** [comment]
has this been merged to the branch or not as i am getting the same error with php 7.2 Yii 2.0.15.1 while trying to create permissions on ajaxValidation. 

I have `dektrium/yii2-rbac 1.0.0-alpha`


And about the above code why not use just 

`return ActiveForm::validate($model)`

instead of 

Yii::$app->response->data = json_encode(ActiveForm::validate($model));

as we are setting the response format to JSON a line before.
