### ISSUE TITLE
dektrium yii2-rbac + yii2-user show Rule class can not be instantiated

### ISSUE THREAD

**Issue by naivejie** [dektrium/yii2-rbac#94]
when i new rule, it show me 'Rule class can not be instantiated' 
i wrote Class field like this 'backend\modules\user\controllers\AdminController' , what's wrong?? pls help.

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
