### ISSUE TITLE
Data field on roles

### ISSUE THREAD

**Issue by evecute** [dektrium/yii2-rbac#97]
hi im new using YIii2 and found this extension. Please can you help me to fill data field on create roles. I got this error message: "Data must be type of JSON (Syntax error.)". I also need documentation how to use this RBAC correctly.
Thanks!

**Comment by becology1100** [comment]
do you got any updates?

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
