### ISSUE TITLE
Problems with composer

### ISSUE THREAD

**Issue by ettolo** [dektrium/yii2-rbac#98]
Hi, 
trying to install a new dependency in one of my project i run composer update and i get this error:

> Failed to download dektrium/yii2-rbac from source: Failed to clone https://github.com/dektrium/yii2-rbac.git, git was not found, check that it is installed and in your PATH env.

in my composer require section i have:

`"dektrium/yii2-user":"0.9.*@dev",
 "dektrium/yii2-rbac": "dev-master",`

yii2-rbac was already in use in this project...

Now running the site i get this error

> Class dektrium\rbac\Module does not exist

What is the problem?
Thank you!

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
